### ISSUE TITLE
Can't get bintray-resource to work

### ISSUE THREAD

**Issue by matthiasbalke** [jamiemonserrate/bintray-resource#1]
I tried to use your custom bintray-resource for concourse.ci. I defined a target repo like that:

``` yaml
resource_types:
- name: bintray
  type: docker-image
  source:
    repository: jamiemonserrate/bintray-resource

- name: bintray-release-candidates
  type: bintray
  source:
    subject_name: reflectoring
    repo_name: infiniboard
    package_name: release-candidates
    username: {{bintray-username}}
    api_key: {{bintray-api-key}}

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:matthiasbalke/concourse_test.git
    branch: version
    file: version
    private_key: {{infiniboard-private-key}}
    initial_version: 1.0.0
```

afterwards used this repo in a job to push an artifact like so:

``` yaml
  - put: bintray-release-candidates
    params:
      from: artifacts/infiniboard-*.jar
      version_file: version/number
```

But the job fails with this error message:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest: 404 Not Found
```

Do you have any ideas, what I'm doing wrong? Does it mean, it can't access my bintray repo?
