### ISSUE TITLE
where is the docker image?

### ISSUE THREAD

**Issue by panpan0000** [jamiemonserrate/bintray-resource#2]
How to use this resource ?
where is the docker image of this resource ?

```
resource_types:
- name: bintray-resource
  type: docker-image
  source:
      repository: jamiemonserrate/bintray-resource
```
